version: "3.0"

services:
  tml:
    container_name: tml
    restart: unless-stopped
    build:
      context: .
      args:
        UID: 1003
        GID: 1003
    tty: true
    stdin_open: true
    ports:
      - 7777:7777
    volumes:
      - ./data:/home/tml/.local/share/Terraria/tModLoader
